apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rateio-online
  name: rateio-online
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rateio-online
  template:
    metadata:
      labels:
        app: rateio-online
    spec:
      containers:
        - image: cbeloni/rateio-online:arm64
          imagePullPolicy: Always
          name: rateio-online
          ports:
            - containerPort: 8000